/* This file is generated by venus-protocol.  See vn_protocol_driver.h. */

/*
 * Copyright 2020 Google LLC
 * SPDX-License-Identifier: MIT
 */

#ifndef VN_PROTOCOL_DRIVER_SURFACE_H
#define VN_PROTOCOL_DRIVER_SURFACE_H

#include "vn_ring.h"
#include "vn_protocol_driver_structs.h"

/* struct VkSurfaceCreateInfoWEBROGUE chain */

static inline size_t
vn_sizeof_VkSurfaceCreateInfoWEBROGUE_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkSurfaceCreateInfoWEBROGUE_self(const VkSurfaceCreateInfoWEBROGUE *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_VkFlags(&val->flags);
    size += vn_sizeof_uint32_t(&val->webrogue_window_id);
    return size;
}

static inline size_t
vn_sizeof_VkSurfaceCreateInfoWEBROGUE(const VkSurfaceCreateInfoWEBROGUE *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkSurfaceCreateInfoWEBROGUE_pnext(val->pNext);
    size += vn_sizeof_VkSurfaceCreateInfoWEBROGUE_self(val);

    return size;
}

static inline void
vn_encode_VkSurfaceCreateInfoWEBROGUE_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkSurfaceCreateInfoWEBROGUE_self(struct vn_cs_encoder *enc, const VkSurfaceCreateInfoWEBROGUE *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_VkFlags(enc, &val->flags);
    vn_encode_uint32_t(enc, &val->webrogue_window_id);
}

static inline void
vn_encode_VkSurfaceCreateInfoWEBROGUE(struct vn_cs_encoder *enc, const VkSurfaceCreateInfoWEBROGUE *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_SURFACE_CREATE_INFO_WEBROGUE);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_SURFACE_CREATE_INFO_WEBROGUE });
    vn_encode_VkSurfaceCreateInfoWEBROGUE_pnext(enc, val->pNext);
    vn_encode_VkSurfaceCreateInfoWEBROGUE_self(enc, val);
}

static inline size_t vn_sizeof_vkDestroySurfaceKHR(VkInstance instance, VkSurfaceKHR surface, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroySurfaceKHR_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkInstance(&instance);
    cmd_size += vn_sizeof_VkSurfaceKHR(&surface);
    cmd_size += vn_sizeof_simple_pointer(pAllocator);
    if (pAllocator)
        assert(false);

    return cmd_size;
}

static inline void vn_encode_vkDestroySurfaceKHR(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkInstance instance, VkSurfaceKHR surface, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroySurfaceKHR_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkInstance(enc, &instance);
    vn_encode_VkSurfaceKHR(enc, &surface);
    if (vn_encode_simple_pointer(enc, pAllocator))
        assert(false);
}

static inline size_t vn_sizeof_vkDestroySurfaceKHR_reply(VkInstance instance, VkSurfaceKHR surface, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroySurfaceKHR_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    /* skip instance */
    /* skip surface */
    /* skip pAllocator */

    return cmd_size;
}

static inline void vn_decode_vkDestroySurfaceKHR_reply(struct vn_cs_decoder *dec, VkInstance instance, VkSurfaceKHR surface, const VkAllocationCallbacks* pAllocator)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkDestroySurfaceKHR_EXT);

    /* skip instance */
    /* skip surface */
    /* skip pAllocator */
}

static inline size_t vn_sizeof_vkCreateSurfaceWEBROGUE(VkInstance instance, const VkSurfaceCreateInfoWEBROGUE* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateSurfaceWEBROGUE_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkInstance(&instance);
    cmd_size += vn_sizeof_simple_pointer(pCreateInfo);
    if (pCreateInfo)
        cmd_size += vn_sizeof_VkSurfaceCreateInfoWEBROGUE(pCreateInfo);
    cmd_size += vn_sizeof_simple_pointer(pAllocator);
    if (pAllocator)
        assert(false);
    cmd_size += vn_sizeof_simple_pointer(pSurface);
    if (pSurface)
        cmd_size += vn_sizeof_VkSurfaceKHR(pSurface);

    return cmd_size;
}

static inline void vn_encode_vkCreateSurfaceWEBROGUE(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkInstance instance, const VkSurfaceCreateInfoWEBROGUE* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateSurfaceWEBROGUE_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkInstance(enc, &instance);
    if (vn_encode_simple_pointer(enc, pCreateInfo))
        vn_encode_VkSurfaceCreateInfoWEBROGUE(enc, pCreateInfo);
    if (vn_encode_simple_pointer(enc, pAllocator))
        assert(false);
    if (vn_encode_simple_pointer(enc, pSurface))
        vn_encode_VkSurfaceKHR(enc, pSurface);
}

static inline size_t vn_sizeof_vkCreateSurfaceWEBROGUE_reply(VkInstance instance, const VkSurfaceCreateInfoWEBROGUE* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateSurfaceWEBROGUE_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    VkResult ret;
    cmd_size += vn_sizeof_VkResult(&ret);
    /* skip instance */
    /* skip pCreateInfo */
    /* skip pAllocator */
    cmd_size += vn_sizeof_simple_pointer(pSurface);
    if (pSurface)
        cmd_size += vn_sizeof_VkSurfaceKHR(pSurface);

    return cmd_size;
}

static inline VkResult vn_decode_vkCreateSurfaceWEBROGUE_reply(struct vn_cs_decoder *dec, VkInstance instance, const VkSurfaceCreateInfoWEBROGUE* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkCreateSurfaceWEBROGUE_EXT);

    VkResult ret;
    vn_decode_VkResult(dec, &ret);
    /* skip instance */
    /* skip pCreateInfo */
    /* skip pAllocator */
    if (vn_decode_simple_pointer(dec)) {
        vn_decode_VkSurfaceKHR(dec, pSurface);
    } else {
        pSurface = NULL;
    }

    return ret;
}

static inline void vn_submit_vkDestroySurfaceKHR(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkInstance instance, VkSurfaceKHR surface, const VkAllocationCallbacks* pAllocator, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkDestroySurfaceKHR(instance, surface, pAllocator);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkDestroySurfaceKHR_reply(instance, surface, pAllocator) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkDestroySurfaceKHR(enc, cmd_flags, instance, surface, pAllocator);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_submit_vkCreateSurfaceWEBROGUE(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkInstance instance, const VkSurfaceCreateInfoWEBROGUE* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkCreateSurfaceWEBROGUE(instance, pCreateInfo, pAllocator, pSurface);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkCreateSurfaceWEBROGUE_reply(instance, pCreateInfo, pAllocator, pSurface) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkCreateSurfaceWEBROGUE(enc, cmd_flags, instance, pCreateInfo, pAllocator, pSurface);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_async_vkDestroySurfaceKHR(struct vn_ring *vn_ring, VkInstance instance, VkSurfaceKHR surface, const VkAllocationCallbacks* pAllocator)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkDestroySurfaceKHR(vn_ring, 0, instance, surface, pAllocator, &submit);
}

static inline VkResult vn_call_vkCreateSurfaceWEBROGUE(struct vn_ring *vn_ring, VkInstance instance, const VkSurfaceCreateInfoWEBROGUE* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface)
{
    VN_TRACE_FUNC();

    struct vn_ring_submit_command submit;
    vn_submit_vkCreateSurfaceWEBROGUE(vn_ring, VK_COMMAND_GENERATE_REPLY_BIT_EXT, instance, pCreateInfo, pAllocator, pSurface, &submit);
    struct vn_cs_decoder *dec = vn_ring_get_command_reply(vn_ring, &submit);
    if (dec) {
        const VkResult ret = vn_decode_vkCreateSurfaceWEBROGUE_reply(dec, instance, pCreateInfo, pAllocator, pSurface);
        vn_ring_free_command_reply(vn_ring, &submit);
        return ret;
    } else {
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    }
}

static inline void vn_async_vkCreateSurfaceWEBROGUE(struct vn_ring *vn_ring, VkInstance instance, const VkSurfaceCreateInfoWEBROGUE* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkCreateSurfaceWEBROGUE(vn_ring, 0, instance, pCreateInfo, pAllocator, pSurface, &submit);
}

#endif /* VN_PROTOCOL_DRIVER_SURFACE_H */
